version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 10
  pre_build:
    commands:
      - npm install -g serverless
  build:
    commands:
      - echo Build started on `date`
      - echo Build Lambda POC Migration
      - cd src/services/poc-migration
      - npm i
      - npm run deploy:dev
      - echo Build Frontend
      - cd -
      - cd src/services/web
      - npm i
      - npm run deploy
  post_build:
    commands:
      - echo Build completed on `date`
  