env:
  browser: true
  es6: true
extends: airbnb
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
  sourceType: module
plugins:
  - react
rules: 
  react/jsx-filename-extension: 
    - 1
    - extensions:
      - ".js"
      - ".jsx"
  jsx-a11y/label-has-for: "off"
  jsx-a11y/label-has-associated-control: "off"
  react/require-default-props: "off"
  import/prefer-default-export: "off"
  react/forbid-prop-types: "off"
  no-plusplus:
    - 2
    - allowForLoopAfterthoughts: true
  no-param-reassign: "off"
  guard-for-in: "off"
  no-underscore-dangle: "off"
  prefer-destructuring: "off"
  no-restricted-syntax:
    - "error"
    - "LabeledStatement"
    - "WithStatement"
  no-unused-expressions: "off"
  global-require: 0
  linebreak-style: 0
  react/prop-types: 0
  radix: 0
  no-empty: "off"
    
   